name: deploy-shinyapps
on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rsconnect"), type = "binary")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: push to shinyapps
        run: |
          rsconnect::setAccountInfo(name='r4dscommunity', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})
          rsconnect::deployApp(appName = 'mentordash')
        shell: Rscript {0}
