name: deploy-shinyapps
on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: push to shinyapps
        run: |
          Rscript -e "install.packages('rsconnect')"
          Rscript -e "rsconnect::setAccountInfo(name='r4dscommunity', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'mentordash')"
