name: pr_check
on:
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  bookdown:
    name: pr_check_shinyapps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect
          cache-version: 1
      - name: push to shinyapps
        run: |
          rsconnect::setAccountInfo(name='r4dscommunity', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})
          rsconnect::deployApp(appName = 'mentordashtest')
        shell: Rscript {0}
